server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./mboacare_data/mboacare_bd;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (optional, accessible via /h2-console)
spring.h2.console.enabled=true
